site_name: Multistate Epigenetic Pacemaker

repo_url: https://github.com/NuttyLogic/MultistateEpigeneticPacemaker
repo_name: 'GitHub'

theme:
  name: 'material'
  logo: img/lightning-bolt.png
  favicon: img/lightning-bolt.png


nav:
    - Home: index.md
    - API: API.md
    - Tutorial: tutorial.md

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
  - pymdownx.arithmatex

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML